services:
  # n8n - Workflow automation (pre-built image)
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
    volumes:
      - n8n_data:/home/node/.n8n

  # Log Generator - Simulates applications producing logs
  log-generator:
    build: 
      context: ./log-generator
      dockerfile: Dockerfile
    container_name: log-generator
    volumes:
      - ./shared-logs:/app/logs

  # Log Analyzer - Processes logs and detects incidents
  log-analyzer:
    build: 
      context: ./log-analyzer
      dockerfile: Dockerfile
    container_name: log-analyzer
    volumes:
      - ./shared-logs:/app/logs:ro
    depends_on:
      - n8n

  # Incident Website - Dashboard for displaying incidents
  incident-website:
    build: 
      context: ./incident-website
      dockerfile: Dockerfile
    container_name: incident-website
    ports:
      - "5000:5000"
    volumes:
      - ./incident-website:/app

volumes:
  n8n_data: