FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY scripts/email_processor.py scripts/
COPY scripts/__init__.py scripts/

EXPOSE 8080

CMD ["python", "scripts/email_processor.py"]