"use client"

import { useDemo } from "../../components/demo-store"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

export default function NotificationsPage() {
  const { state, markAllRead } = useDemo()

  return (
    <div className="space-y-6">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Notifications</h1>
          <p className="text-sm text-muted-foreground">Alerts generated by modules in this demo.</p>
        </div>
        <Button variant="secondary" onClick={markAllRead}>
          Mark all as read
        </Button>
      </header>

      <div className="grid gap-3">
        {state.notifications.map((n) => (
          <Card key={n.id}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0">
              <CardTitle className="text-base">{n.title}</CardTitle>
              <Badge variant={n.severity === "Critical" ? "destructive" : "default"}>{n.severity}</Badge>
            </CardHeader>
            <CardContent className="flex items-center justify-between gap-4 text-sm">
              <div className="text-muted-foreground">
                <p className="line-clamp-2">{n.body}</p>
                <p className="mt-1 text-xs">{new Date(n.timestamp).toLocaleString()}</p>
              </div>
              <Button asChild size="sm">
                <Link href={n.link || "/"}>Open</Link>
              </Button>
            </CardContent>
          </Card>
        ))}
        {state.notifications.length === 0 && (
          <div className="rounded-md border bg-card p-4 text-sm text-muted-foreground">No notifications.</div>
        )}
      </div>
    </div>
  )
}
